from __future__ import annotations

import argparse
from datetime import datetime

from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


def configure_page(doc: Document) -> None:
    section = doc.sections[0]
    section.page_width = Inches(8.27)  # A4 portrait
    section.page_height = Inches(11.69)
    section.left_margin = Inches(0.9)
    section.right_margin = Inches(0.9)
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.orientation = WD_ORIENT.PORTRAIT


def set_default_font(doc: Document, font_name: str = "Calibri", size: int = 11) -> None:
    normal = doc.styles["Normal"]
    normal.font.name = font_name
    normal.font.size = Pt(size)
    normal._element.rPr.rFonts.set(qn("w:eastAsia"), font_name)


def add_cover_page(
    doc: Document,
    company_name: str,
    prepared_by: str,
    version: str,
    app_name: str,
    generated_on: str,
) -> None:
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run(company_name)
    run.bold = True
    run.font.size = Pt(24)
    run.font.color.rgb = RGBColor(31, 41, 55)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"User Manual for {app_name}")
    run.bold = True
    run.font.size = Pt(18)
    run.font.color.rgb = RGBColor(17, 24, 39)

    doc.add_paragraph()

    meta = doc.add_table(rows=5, cols=2)
    meta.style = "Table Grid"
    meta.cell(0, 0).text = "Document Title"
    meta.cell(0, 1).text = f"{app_name} - Mobile End User Manual"
    meta.cell(1, 0).text = "Version"
    meta.cell(1, 1).text = version
    meta.cell(2, 0).text = "Prepared For"
    meta.cell(2, 1).text = company_name
    meta.cell(3, 0).text = "Prepared By"
    meta.cell(3, 1).text = prepared_by
    meta.cell(4, 0).text = "Date"
    meta.cell(4, 1).text = generated_on

    for row in meta.rows:
        for idx, cell in enumerate(row.cells):
            for paragraph in cell.paragraphs:
                for item in paragraph.runs:
                    if idx == 0:
                        item.bold = True

    doc.add_paragraph()
    note = doc.add_paragraph(
        "Confidential: This document is intended for authorized mobile operations and warehouse teams only."
    )
    note.alignment = WD_ALIGN_PARAGRAPH.CENTER
    note.runs[0].italic = True

    doc.add_page_break()


def add_heading(doc: Document, text: str, level: int = 1) -> None:
    heading = doc.add_heading(text, level=level)
    if heading.runs:
        heading.runs[0].font.color.rgb = RGBColor(17, 24, 39)


def add_bullet_points(doc: Document, items: list[str]) -> None:
    for item in items:
        paragraph = doc.add_paragraph(item, style="List Bullet")
        paragraph.paragraph_format.space_after = Pt(3)


def add_numbered_steps(doc: Document, steps: list[str]) -> None:
    for step in steps:
        paragraph = doc.add_paragraph(step, style="List Number")
        paragraph.paragraph_format.space_after = Pt(4)


def add_table_of_contents(doc: Document) -> None:
    add_heading(doc, "Table of Contents", level=1)
    entries = [
        "1. Document Purpose",
        "2. Product Overview",
        "3. User Roles and Access",
        "4. Mobile Navigation and Screen Guide",
        "5. Functional Workflows",
        "6. Feature Module Step-by-Step Guide (With Do Not Modify Notes)",
        "7. Settings and Configuration",
        "8. Data Model and Status Lifecycle",
        "9. Troubleshooting",
        "10. Data and Security Notes",
        "11. Support and Escalation",
    ]
    for entry in entries:
        doc.add_paragraph(entry)
    doc.add_paragraph("Note: This is a static contents section generated by script.").runs[0].italic = True


def add_purpose_section(doc: Document, app_name: str) -> None:
    add_heading(doc, "1. Document Purpose", level=1)
    doc.add_paragraph(
        f"This manual explains day-to-day use of the {app_name} mobile application for yarn operations. "
        "It is intended for floor operators, dispatch teams, and administrators who manage inventory movement through QR scanning."
    )
    add_bullet_points(
        doc,
        [
            "Standardize yarn intake, movement verification, and dispatch confirmation from mobile devices.",
            "Reduce manual tracking errors through QR-based validation.",
            "Provide fast onboarding steps for operational users.",
            "Define support and escalation guidance for scan or sync issues.",
        ],
    )


def add_overview_and_roles(doc: Document, app_name: str) -> None:
    add_heading(doc, "2. Product Overview", level=1)
    doc.add_paragraph(
        f"{app_name} is a Flutter-based mobile app connected to Firebase. "
        "It allows operators to scan yarn QR codes, auto-assign storage location for new rolls, "
        "move reserved stock to dispatch state, and complete dispatch validation."
    )
    add_bullet_points(
        doc,
        [
            "Mobile platform: Android-compatible Flutter app.",
            "Backend/data source: Cloud Firestore (real-time updates).",
            "Scanner engine: in-app camera QR scanner.",
            "Core modules: Welcome, Home, Reserved List, Dispatch List, Add Yarn Scan, Settings.",
        ],
    )

    add_heading(doc, "3. User Roles and Access", level=1)
    roles = doc.add_table(rows=1, cols=3)
    roles.style = "Table Grid"
    roles.rows[0].cells[0].text = "Role"
    roles.rows[0].cells[1].text = "Primary Responsibilities"
    roles.rows[0].cells[2].text = "Typical Mobile Screens"

    role_data = [
        (
            "Warehouse Operator",
            "Scan and add new yarn rolls, verify yarn identity, check roll details.",
            "Home, Scan to Add, Yarn Details",
        ),
        (
            "Floor Movement Operator",
            "Move reserved yarn to waiting-for-dispatch after QR verification.",
            "Reserved List, Scan to Verify",
        ),
        (
            "Dispatch Operator",
            "Verify moved yarn and mark as dispatched.",
            "Dispatch List, Scan to Verify",
        ),
        (
            "Inventory Admin",
            "Maintain inventory rules such as bin capacity, weight limits, and max bins.",
            "Settings",
        ),
    ]

    for role, responsibility, screens in role_data:
        row = roles.add_row().cells
        row[0].text = role
        row[1].text = responsibility
        row[2].text = screens

    for row in roles.rows:
        for idx, cell in enumerate(row.cells):
            if row == roles.rows[0] or idx == 0:
                for paragraph in cell.paragraphs:
                    for item in paragraph.runs:
                        item.bold = True


def add_navigation_section(doc: Document) -> None:
    add_heading(doc, "4. Mobile Navigation and Screen Guide", level=1)
    doc.add_paragraph(
        "After launch, users land on the Welcome screen and proceed to the home dashboard. "
        "From the dashboard, users open operational modules using cards and top-right settings."
    )

    add_bullet_points(
        doc,
        [
            "Welcome: animated intro and Get Started button.",
            "Home Dashboard: entry cards for Reserved List, Dispatch List, and Add Yarn.",
            "Reserved List: list of reserved yarn waiting for move verification.",
            "Dispatch List: list of moved yarn waiting for dispatch confirmation.",
            "Scan Screen: camera scanner for add/verify actions.",
            "Yarn Details: scanned roll information and confirmation actions.",
            "Settings: inventory rule configuration.",
        ],
    )

    add_heading(doc, "Screen Catalog", level=2)
    catalog = doc.add_table(rows=1, cols=2)
    catalog.style = "Table Grid"
    catalog.rows[0].cells[0].text = "Screen"
    catalog.rows[0].cells[1].text = "Business Purpose"

    screens = [
        ("Welcome", "Launch point with app branding and navigation to the dashboard."),
        ("Main Dashboard", "Central navigation to reserved, dispatch, and add flows."),
        (
            "Reserved List",
            "Shows reserved items; swipe and scan to validate move to waiting-for-dispatch.",
        ),
        (
            "Dispatch List",
            "Shows moved items; scan verification marks yarn as dispatched.",
        ),
        ("Scan to Add", "Scan a yarn QR and open confirmation with auto-allocation."),
        (
            "Yarn Details",
            "Displays parsed yarn data; confirms add/move/dispatch and supports PDF export.",
        ),
        ("Settings", "Manage limits used by auto-allocation logic."),
    ]

    for name, purpose in screens:
        row = catalog.add_row().cells
        row[0].text = name
        row[1].text = purpose


def add_workflow_section(doc: Document) -> None:
    add_heading(doc, "5. Functional Workflows", level=1)

    add_heading(doc, "Workflow A: Add New Yarn via QR", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Home Dashboard and tap Add Yarn.",
            "Scan the yarn QR code using the camera scanner.",
            "Review parsed yarn fields on the details screen.",
            "Verify suggested rack/bin from auto-allocation (or manually adjust if needed).",
            "Confirm to save; yarn is created in inventory with IN STOCK state.",
        ],
    )

    add_heading(doc, "Workflow B: Move Reserved Yarn to Dispatch Queue", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Reserved List and locate the yarn ID (use search if required).",
            "Swipe the item toward scan action and complete QR verification.",
            "On successful match, confirm move action.",
            "System updates state to waiting for dispatch.",
        ],
    )

    add_heading(doc, "Workflow C: Dispatch Yarn", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Dispatch List and select a ready yarn entry.",
            "Scan the yarn QR to verify identity.",
            "Confirm dispatch action from details screen.",
            "System marks state as DISPATCHED in reserved and inventory records.",
        ],
    )

    add_heading(doc, "Workflow D: Remove Invalid or Cancelled Entry", level=2)
    add_numbered_steps(
        doc,
        [
            "From Reserved List or Dispatch List, swipe to the remove direction.",
            "Confirm removal in the dialog.",
            "System updates or removes the reserved entry according to workflow rules.",
        ],
    )


def add_feature_module_guide(doc: Document) -> None:
    add_heading(doc, "6. Feature Module Step-by-Step Guide (With Do Not Modify Notes)", level=1)
    doc.add_paragraph(
        "This section gives clear module-wise usage steps for operators. "
        "Each module also includes fields and controls that must not be modified by end users."
    )

    modules = [
        {
            "name": "Welcome Module",
            "purpose": "Start the app and navigate to the operational dashboard.",
            "steps": [
                "Open the app and wait for the welcome animation to complete.",
                "Tap Get Started to enter the dashboard.",
                "If the app is slow, wait until dashboard cards are visible before tapping.",
            ],
            "do_not_modify": [
                "Do not change welcome text, logo, or animation behavior.",
                "Do not bypass startup by altering navigation flow.",
            ],
        },
        {
            "name": "Home Dashboard Module",
            "purpose": "Open Reserved List, Dispatch List, Add Yarn, and Settings.",
            "steps": [
                "Use Reserved List card for move verification tasks.",
                "Use Dispatch List card for final dispatch verification.",
                "Use Add Yarn card to register newly scanned yarn rolls.",
                "Use top-right Settings only when authorized.",
            ],
            "do_not_modify": [
                "Do not rename cards or change module routing.",
                "Do not alter role-based access expectations from dashboard entries.",
            ],
        },
        {
            "name": "Reserved List Module",
            "purpose": "Move reserved yarn to waiting-for-dispatch after scan validation.",
            "steps": [
                "Open Reserved List and identify the yarn row.",
                "Swipe for scan action and scan the exact roll QR.",
                "Confirm move only after ID match is displayed.",
                "Recheck that item status changes to waiting for dispatch.",
            ],
            "do_not_modify": [
                "Do not manually edit yarn ID/state from this screen.",
                "Do not skip scan verification before confirming move.",
            ],
        },
        {
            "name": "Dispatch List Module",
            "purpose": "Complete final dispatch of moved yarn after scan validation.",
            "steps": [
                "Open Dispatch List and select the pending item.",
                "Scan the yarn QR code to verify identity.",
                "Confirm dispatch to finalize movement.",
                "Verify status reflects DISPATCHED.",
            ],
            "do_not_modify": [
                "Do not dispatch any item without successful scan match.",
                "Do not alter dispatch status through manual database edits.",
            ],
        },
        {
            "name": "Scan to Add Yarn Module",
            "purpose": "Add new yarn roll records using QR data and auto-allocation.",
            "steps": [
                "Open Add Yarn and scan a clear QR code.",
                "Review parsed yarn fields on details page.",
                "Validate suggested rack/bin allocation.",
                "Confirm to save inventory entry.",
            ],
            "do_not_modify": [
                "Do not change immutable QR-origin identity fields.",
                "Do not override allocation constraints beyond allowed policy.",
            ],
        },
        {
            "name": "Yarn Details Module",
            "purpose": "Review scanned information and confirm add/move/dispatch action.",
            "steps": [
                "Check all visible yarn attributes for correctness.",
                "Choose the intended action (add, move, or dispatch).",
                "Use PDF export only for approved reporting needs.",
                "Submit confirmation and wait for success message.",
            ],
            "do_not_modify": [
                "Do not edit system-managed lifecycle values directly.",
                "Do not export or share details outside approved process.",
            ],
        },
        {
            "name": "Settings Module",
            "purpose": "Maintain inventory rule limits used by allocation logic.",
            "steps": [
                "Open Settings with admin authorization.",
                "Update only required numeric limits.",
                "Save and verify confirmation message.",
                "Run a test add flow to validate rule behavior.",
            ],
            "do_not_modify": [
                "Do not reduce protected thresholds below operationally safe values.",
                "Do not change settings without admin approval and change record.",
            ],
        },
    ]

    for module in modules:
        add_heading(doc, module["name"], level=2)
        doc.add_paragraph(f"Purpose: {module['purpose']}")

        doc.add_paragraph("How to Use:").runs[0].bold = True
        add_numbered_steps(doc, module["steps"])

        doc.add_paragraph("Do Not Modify:").runs[0].bold = True
        add_bullet_points(doc, module["do_not_modify"])


def add_settings_and_lifecycle(doc: Document) -> None:
    add_heading(doc, "7. Settings and Configuration", level=1)
    doc.add_paragraph("Inventory settings control automatic placement and capacity checks.")
    add_bullet_points(
        doc,
        [
            "Max Rolls per Bin (bin_capacity): upper roll count per bin.",
            "Max Weight per Bin (max_bin_weight): allowed total weight per bin.",
            "Max Bins per Rack (max_bins): search limit for auto-allocation.",
            "Validation does not allow reducing key limits below current protected thresholds.",
        ],
    )

    add_heading(doc, "8. Data Model and Status Lifecycle", level=1)
    add_bullet_points(
        doc,
        [
            "Primary inventory collection: yarnRolls.",
            "Movement queue collection: reserved_collection.",
            "Configuration document: config/inventory_rules.",
            "Common lifecycle states: IN STOCK -> RESERVED -> waiting for dispatch -> DISPATCHED.",
            "Cancellation path may mark record as cancelled when removed from dispatch flow.",
        ],
    )

    add_heading(doc, "Status Transition Table", level=2)
    status_table = doc.add_table(rows=1, cols=3)
    status_table.style = "Table Grid"
    status_table.rows[0].cells[0].text = "Current State"
    status_table.rows[0].cells[1].text = "Action"
    status_table.rows[0].cells[2].text = "Next State"

    transitions = [
        ("IN STOCK", "Reserved by planning/order process", "RESERVED"),
        ("RESERVED", "Verified move from Reserved List", "waiting for dispatch"),
        ("waiting for dispatch", "Verified in Dispatch List", "DISPATCHED"),
        ("waiting for dispatch", "Removed/cancelled from dispatch flow", "cancelled"),
    ]
    for current, action, nxt in transitions:
        row = status_table.add_row().cells
        row[0].text = current
        row[1].text = action
        row[2].text = nxt


def add_troubleshooting(doc: Document) -> None:
    add_heading(doc, "9. Troubleshooting", level=1)
    table = doc.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    table.rows[0].cells[0].text = "Issue"
    table.rows[0].cells[1].text = "Likely Cause"
    table.rows[0].cells[2].text = "Resolution"

    items = [
        (
            "Scanner opens but does not detect QR",
            "Poor camera focus, lighting issue, or damaged QR",
            "Improve lighting, hold steady, retry with clear print, and verify camera permission.",
        ),
        (
            "Scanned yarn marked invalid during move/dispatch",
            "Scanned code does not match expected yarn ID",
            "Confirm selected list item and rescan the correct roll label.",
        ),
        (
            "Unable to add yarn",
            "Missing weight/required fields or no available bin capacity",
            "Check yarn QR payload, confirm weight, and review inventory limits in Settings.",
        ),
        (
            "Settings not saved",
            "Validation failure or Firestore write error",
            "Use valid values, ensure network access, and retry as admin user.",
        ),
        (
            "List data not updating",
            "Network delay or Firebase connectivity issue",
            "Verify internet availability and reload the page.",
        ),
    ]

    for issue, cause, resolution in items:
        row = table.add_row().cells
        row[0].text = issue
        row[1].text = cause
        row[2].text = resolution


def add_security_and_support(doc: Document) -> None:
    add_heading(doc, "10. Data and Security Notes", level=1)
    add_bullet_points(
        doc,
        [
            "Use authorized user devices only for scanning and dispatch operations.",
            "Keep device screen lock enabled and do not share operational credentials.",
            "Follow role separation for settings updates and dispatch confirmation.",
            "Retain operational logs and exported PDFs as per internal audit policy.",
        ],
    )

    add_heading(doc, "11. Support and Escalation", level=1)
    doc.add_paragraph("Recommended escalation flow for mobile operational incidents:")
    add_numbered_steps(
        doc,
        [
            "Operator captures screenshot, yarn ID, and timestamp.",
            "Inventory admin validates user action and retries workflow.",
            "If unresolved, escalate with app logs and Firestore document IDs.",
            "Record root cause and corrective action in incident register.",
        ],
    )

    add_heading(doc, "Appendix A: Firestore Reference", level=2)
    api_table = doc.add_table(rows=1, cols=2)
    api_table.style = "Table Grid"
    api_table.rows[0].cells[0].text = "Collection / Document"
    api_table.rows[0].cells[1].text = "Purpose"

    entries = [
        ("config/inventory_rules", "Stores bin capacity, weight, and rack bin limits."),
        ("yarnRolls", "Main yarn inventory records and current states."),
        ("reserved_collection", "Reserved and moved yarn queue for movement/dispatch."),
        ("racks", "Rack registry used by allocation workflow."),
        ("bins", "Bin-to-rack linkage records."),
    ]

    for key, purpose in entries:
        row = api_table.add_row().cells
        row[0].text = key
        row[1].text = purpose


def build_manual(
    output: str,
    company_name: str,
    prepared_by: str,
    version: str,
    app_name: str,
) -> None:
    doc = Document()
    configure_page(doc)
    set_default_font(doc)

    generated_on = datetime.now().strftime("%d %B %Y")

    add_cover_page(doc, company_name, prepared_by, version, app_name, generated_on)
    add_table_of_contents(doc)
    add_purpose_section(doc, app_name)
    add_overview_and_roles(doc, app_name)
    add_navigation_section(doc)
    add_workflow_section(doc)
    add_feature_module_guide(doc)
    add_settings_and_lifecycle(doc)
    add_troubleshooting(doc)
    add_security_and_support(doc)

    doc.save(output)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a professional DOCX user manual for the Yarn Scanner mobile application."
    )
    parser.add_argument(
        "--output",
        default="Yarn_Scanner_Mobile_User_Manual.docx",
        help="Output DOCX file path",
    )
    parser.add_argument(
        "--company",
        default="Client Company",
        help="Company name displayed on the cover page",
    )
    parser.add_argument(
        "--prepared-by",
        default="Implementation Team",
        help="Prepared-by value on the cover page",
    )
    parser.add_argument(
        "--version",
        default="1.0",
        help="Document version",
    )
    parser.add_argument(
        "--app-name",
        default="Yarn Scanner",
        help="Application name shown in the manual",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    build_manual(
        output=args.output,
        company_name=args.company,
        prepared_by=args.prepared_by,
        version=args.version,
        app_name=args.app_name,
    )
    print(f"Mobile user manual created successfully: {args.output}")


if __name__ == "__main__":
    main()
