from __future__ import annotations

import argparse
from datetime import datetime

from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


def configure_page(doc: Document) -> None:
    section = doc.sections[0]
    section.page_width = Inches(8.27)   # A4 portrait
    section.page_height = Inches(11.69)
    section.left_margin = Inches(0.9)
    section.right_margin = Inches(0.9)
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.orientation = WD_ORIENT.PORTRAIT


def set_default_font(doc: Document, font_name: str = "Calibri", size: int = 11) -> None:
    normal = doc.styles["Normal"]
    normal.font.name = font_name
    normal.font.size = Pt(size)
    normal._element.rPr.rFonts.set(qn("w:eastAsia"), font_name)


def add_cover_page(
    doc: Document,
    company_name: str,
    prepared_by: str,
    version: str,
    app_name: str,
    generated_on: str,
) -> None:
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = p.add_run(company_name)
    run.bold = True
    run.font.size = Pt(24)
    run.font.color.rgb = RGBColor(31, 41, 55)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"User Manual for {app_name}")
    run.bold = True
    run.font.size = Pt(18)
    run.font.color.rgb = RGBColor(17, 24, 39)

    doc.add_paragraph()

    meta = doc.add_table(rows=5, cols=2)
    meta.style = "Table Grid"
    meta.cell(0, 0).text = "Document Title"
    meta.cell(0, 1).text = f"{app_name} - End User Manual"
    meta.cell(1, 0).text = "Version"
    meta.cell(1, 1).text = version
    meta.cell(2, 0).text = "Prepared For"
    meta.cell(2, 1).text = company_name
    meta.cell(3, 0).text = "Prepared By"
    meta.cell(3, 1).text = prepared_by
    meta.cell(4, 0).text = "Date"
    meta.cell(4, 1).text = generated_on

    for row in meta.rows:
        for idx, cell in enumerate(row.cells):
            for par in cell.paragraphs:
                for r in par.runs:
                    if idx == 0:
                        r.bold = True

    doc.add_paragraph()
    note = doc.add_paragraph(
        "Confidential: This document is intended for authorized client personnel and operational teams only."
    )
    note.alignment = WD_ALIGN_PARAGRAPH.CENTER
    note.runs[0].italic = True

    doc.add_page_break()


def add_heading(doc: Document, text: str, level: int = 1) -> None:
    h = doc.add_heading(text, level=level)
    if h.runs:
        h.runs[0].font.color.rgb = RGBColor(17, 24, 39)


def add_bullet_points(doc: Document, items: list[str]) -> None:
    for item in items:
        p = doc.add_paragraph(item, style="List Bullet")
        p.paragraph_format.space_after = Pt(3)


def add_numbered_steps(doc: Document, steps: list[str]) -> None:
    for step in steps:
        p = doc.add_paragraph(step, style="List Number")
        p.paragraph_format.space_after = Pt(4)


def add_table_of_contents(doc: Document) -> None:
    add_heading(doc, "Table of Contents", level=1)
    entries = [
        "1. Document Purpose",
        "2. Product Overview",
        "3. User Roles and Access",
        "4. Application Navigation",
        "5. Functional Workflows",
        "6. Module-Wise Step-by-Step Usage",
        "7. Do Not Modify (Control Guidelines)",
        "8. Settings and Configuration",
        "9. Reports and Monitoring",
        "10. Troubleshooting",
        "11. Data and Security Notes",
        "12. Support and Escalation",
    ]
    for entry in entries:
        doc.add_paragraph(entry)
    doc.add_paragraph("Note: This is a static contents section generated by script.").runs[0].italic = True


def add_purpose_section(doc: Document, app_name: str) -> None:
    add_heading(doc, "1. Document Purpose", level=1)
    doc.add_paragraph(
        f"This user manual explains daily operations of the {app_name}. "
        "It is designed for warehouse supervisors, inventory operators, dispatch teams, and administrators."
    )
    add_bullet_points(
        doc,
        [
            "Standardize yarn roll intake, storage tracking, reservations, and dispatch.",
            "Provide clear guidance to reduce handling errors.",
            "Enable faster onboarding for client teams.",
            "Define escalation and support procedures.",
        ],
    )


def add_overview_section(doc: Document, app_name: str) -> None:
    add_heading(doc, "2. Product Overview", level=1)
    doc.add_paragraph(
        f"{app_name} is a desktop-hosted warehouse tracking solution with a built-in backend service and browser-based operational screens."
    )
    add_bullet_points(
        doc,
        [
            "Desktop shell: starts system and displays the operational interface.",
            "Backend service: handles APIs, data sync, and QR generation.",
            "Operational pages: dashboard, ordering, approvals, QR gallery/testing, dispatch, and settings.",
            "Data source: cloud-backed inventory and order records.",
        ],
    )

    add_heading(doc, "3. User Roles and Access", level=1)
    roles = doc.add_table(rows=1, cols=3)
    roles.style = "Table Grid"
    hdr = roles.rows[0].cells
    hdr[0].text = "Role"
    hdr[1].text = "Primary Responsibilities"
    hdr[2].text = "Typical Screens"

    role_data = [
        (
            "Inventory Operator",
            "Register new rolls, maintain accurate roll metadata, monitor available stock.",
            "Inventory Dashboard, Bulk Intake, Roll Details",
        ),
        (
            "Order Request User",
            "Create customer orders with yarn quality and quantity.",
            "Place Order",
        ),
        (
            "Admin Approver",
            "Review pending orders, approve or clear items, monitor alerts.",
            "Admin Approval Panel",
        ),
        (
            "Dispatch Team",
            "View and confirm dispatched records and reconcile stock movement.",
            "Dispatched Report",
        ),
        (
            "System Administrator",
            "Adjust system settings, monitor health and troubleshoot environment issues.",
            "Settings, Dashboard, Service Health",
        ),
    ]

    for role, responsibility, screens in role_data:
        row = roles.add_row().cells
        row[0].text = role
        row[1].text = responsibility
        row[2].text = screens

    for row in roles.rows:
        for i, cell in enumerate(row.cells):
            if row == roles.rows[0] or i == 0:
                for p in cell.paragraphs:
                    for r in p.runs:
                        r.bold = True


def add_navigation_section(doc: Document) -> None:
    add_heading(doc, "4. Application Navigation", level=1)
    doc.add_paragraph(
        "After launch, users access the top navigation bar to move between modules. Core navigation entries include:"
    )
    add_bullet_points(
        doc,
        [
            "Inventory Dashboard",
            "Admin Approvals",
            "Place Order",
            "QR Gallery",
            "QR for Testing",
            "Dispatched",
            "Settings",
        ],
    )

    add_heading(doc, "Screen Catalog", level=2)
    catalog = doc.add_table(rows=1, cols=2)
    catalog.style = "Table Grid"
    catalog.rows[0].cells[0].text = "Screen"
    catalog.rows[0].cells[1].text = "Business Purpose"

    screens = [
        ("Inventory Dashboard", "Track real-time stock status, bin/rack occupancy, and analytics."),
        ("Order Yarn / Place Order", "Create order requests by customer and yarn quality."),
        ("Admin Approval Panel", "Validate and approve pending orders."),
        ("Bulk Intake", "Import or register multiple rolls efficiently."),
        ("Roll Details", "Inspect roll attributes and status history."),
        ("QR Gallery", "Review generated QR code images for rolls."),
        ("QR for Testing", "Create and validate testing QR flows."),
        ("Dispatched Report", "Review outbound/dispatched roll history."),
        ("Settings", "Manage capacity and operational thresholds."),
    ]
    for name, purpose in screens:
        row = catalog.add_row().cells
        row[0].text = name
        row[1].text = purpose


def add_workflow_section(doc: Document) -> None:
    add_heading(doc, "5. Functional Workflows", level=1)

    add_heading(doc, "Workflow A: Register New Yarn Roll", level=2)
    add_numbered_steps(
        doc,
        [
            "Open intake screen (single or bulk).",
            "Enter mandatory roll details: yarn type, weight, lot/order identifiers, rack, and bin.",
            "Submit the form to create the roll record.",
            "Verify that state is set to IN STOCK and QR is generated.",
            "Cross-check roll visibility on inventory dashboard.",
        ],
    )

    add_heading(doc, "Workflow B: Place and Approve Order", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Place Order screen and enter customer name.",
            "Add one or more line items with yarn quality and requested quantity.",
            "Submit order and wait for pending confirmation.",
            "Admin opens Admin Approval Panel and validates stock fit.",
            "Admin approves order; system transitions relevant rolls to reserved/next state.",
        ],
    )

    add_heading(doc, "Workflow C: Dispatch and Reconciliation", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Dispatched module to view completed outbound records.",
            "Validate order IDs, roll IDs, and dispatch timestamps.",
            "Confirm physical movement with warehouse logs.",
            "Escalate mismatches to administrator for correction.",
        ],
    )


def add_module_steps_section(doc: Document) -> None:
    add_heading(doc, "6. Module-Wise Step-by-Step Usage", level=1)
    doc.add_paragraph(
        "Use this section as the day-to-day SOP. Follow each module process in the listed order."
    )

    add_heading(doc, "6.1 Inventory Dashboard", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Dashboard from top menu.",
            "Click Refresh to load latest inventory and status cards.",
            "Review IN STOCK, RESERVED, and DISPATCHED summary blocks.",
            "Use filters/search to locate yarn type, rack, bin, or roll ID.",
            "Open roll details from list/cards for verification before any action.",
        ],
    )

    add_heading(doc, "6.2 Place Order Module", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Place Order screen.",
            "Enter Customer Name exactly as approved in client records.",
            "Select Yarn Quality in first item row.",
            "Enter quantity (rolls).",
            "Use Add Another Item for multi-quality orders.",
            "Click Confirm Order.",
            "Verify success confirmation message and inform Admin Approver.",
        ],
    )

    add_heading(doc, "6.3 Admin Approvals Module", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Admin Approval Panel.",
            "Check Pending Orders count and newest requests.",
            "Use search/filter by customer, order ID, or yarn type.",
            "Open each order and verify stock availability.",
            "Approve only after stock and quantity are validated.",
            "Use clear/delete actions only for invalid or duplicate requests.",
            "Re-check Approved tab to confirm order moved successfully.",
        ],
    )

    add_heading(doc, "6.4 Bulk Intake Module", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Bulk Intake.",
            "Upload or enter batch roll data using approved format.",
            "Validate mandatory fields: yarn type, weight, lot/order, rack, bin.",
            "Submit intake batch.",
            "Confirm roll count created matches source sheet.",
            "Open QR Gallery to ensure QRs are generated for new rolls.",
        ],
    )

    add_heading(doc, "6.5 Roll Details Module", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Roll Details from dashboard/list/search results.",
            "Verify roll identity (ID, yarn type, lot number).",
            "Check current state and last state change timestamp.",
            "Review rack/bin assignment before physical movement.",
            "Escalate mismatch immediately to system administrator.",
        ],
    )

    add_heading(doc, "6.6 QR Gallery Module", level=2)
    add_numbered_steps(
        doc,
        [
            "Open QR Gallery.",
            "Search by roll ID or batch if required.",
            "Open QR preview and verify it maps to correct roll data.",
            "Download/print QR only from authorized workstation.",
            "Report missing QR entries via support escalation flow.",
        ],
    )

    add_heading(doc, "6.7 QR for Testing Module", level=2)
    add_numbered_steps(
        doc,
        [
            "Open QR for Testing screen.",
            "Create test QR records only for QA/training scenarios.",
            "Run scan validation and verify decoded values.",
            "Delete test records after completion to avoid production confusion.",
            "Never use test roll IDs for live dispatch or approval.",
        ],
    )

    add_heading(doc, "6.8 Dispatched Module", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Dispatched report.",
            "Review dispatch entries by date/order/roll.",
            "Cross-check with physical gate pass or shipment proof.",
            "Raise discrepancy ticket if any roll is missing or duplicated.",
            "Close daily dispatch log after reconciliation.",
        ],
    )

    add_heading(doc, "6.9 Settings Module", level=2)
    add_numbered_steps(
        doc,
        [
            "Open Settings as authorized administrator only.",
            "Review existing values before applying any change.",
            "Update Rolls per Bin, Max Bin Weight, or Bins per Rack as approved.",
            "Click Apply System Changes.",
            "Confirm save notification and log change in operations register.",
        ],
    )


def add_do_not_modify_section(doc: Document) -> None:
    add_heading(doc, "7. Do Not Modify (Control Guidelines)", level=1)
    doc.add_paragraph(
        "The following controls must not be modified by regular users. Changes are allowed only through authorized administrators with documented approval."
    )
    add_bullet_points(
        doc,
        [
            "Do not modify API URLs, port numbers, or backend runtime configuration.",
            "Do not reduce bin capacity or rack limits below active operating values without migration planning.",
            "Do not edit or delete production roll records directly for convenience.",
            "Do not use bulk delete actions in production unless approved by operations head.",
            "Do not mix test roll data with live dispatch and approval workflows.",
            "Do not rename roll IDs or order IDs manually outside system process.",
            "Do not alter QR image files directly from storage folders.",
            "Do not change settings during active dispatch window unless incident-critical.",
        ],
    )


def add_settings_and_reports(doc: Document) -> None:
    add_heading(doc, "8. Settings and Configuration", level=1)
    doc.add_paragraph("System configuration controls rack and bin behavior.")
    add_bullet_points(
        doc,
        [
            "Rolls per Bin: maximum capacity per bin.",
            "Max Bin Weight: safety threshold in kg.",
            "Bins per Rack: vertical bin count per rack.",
            "Validation guardrails prevent unsafe reduction of active limits.",
        ],
    )

    add_heading(doc, "9. Reports and Monitoring", level=1)
    add_bullet_points(
        doc,
        [
            "Inventory Dashboard: stock levels and category visibility.",
            "Admin metrics: pending and approved counts.",
            "Dispatched report: historical outbound movements.",
            "Health endpoint monitoring for backend availability.",
        ],
    )


def add_troubleshooting(doc: Document) -> None:
    add_heading(doc, "10. Troubleshooting", level=1)
    table = doc.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    table.rows[0].cells[0].text = "Issue"
    table.rows[0].cells[1].text = "Likely Cause"
    table.rows[0].cells[2].text = "Resolution"

    items = [
        (
            "Application loads but screen remains blank",
            "Backend service not running or unreachable",
            "Restart app and verify service health endpoint. Ensure local port 5000 is available.",
        ),
        (
            "Order submission fails",
            "Network issue or invalid input values",
            "Check required fields, retry, then inspect backend logs if repeated.",
        ),
        (
            "QR image missing for a roll",
            "QR generation interrupted during write",
            "Reload inventory to trigger self-healing QR generation and confirm file access permissions.",
        ),
        (
            "Settings not saved",
            "Validation rule violation or API failure",
            "Use allowed threshold values and retry. Verify settings API response.",
        ),
        (
            "Old test records visible in production view",
            "Testing data not cleaned",
            "Use cleanup function or admin delete endpoints for test-roll records.",
        ),
    ]

    for issue, cause, resolution in items:
        row = table.add_row().cells
        row[0].text = issue
        row[1].text = cause
        row[2].text = resolution


def add_data_security_support(doc: Document) -> None:
    add_heading(doc, "11. Data and Security Notes", level=1)
    add_bullet_points(
        doc,
        [
            "Use role-based process control for order approvals and settings changes.",
            "Maintain regular backup/export policy for inventory and order data.",
            "Avoid sharing raw operational endpoints with unauthorized users.",
            "Use only validated devices for scanning and dispatch operations.",
        ],
    )

    add_heading(doc, "12. Support and Escalation", level=1)
    doc.add_paragraph("Recommended escalation flow for operational incidents:")
    add_numbered_steps(
        doc,
        [
            "Operator reports issue with screenshot and timestamp.",
            "System admin performs first-level validation and retry.",
            "If unresolved, escalate to technical support with logs and affected IDs.",
            "Capture root cause and corrective action in incident register.",
        ],
    )

    add_heading(doc, "Appendix A: Core API Reference (Operational)", level=2)
    api_table = doc.add_table(rows=1, cols=2)
    api_table.style = "Table Grid"
    api_table.rows[0].cells[0].text = "Endpoint"
    api_table.rows[0].cells[1].text = "Usage"

    endpoints = [
        ("GET /api/health", "Service health check"),
        ("GET /api/rolls", "Fetch inventory rolls"),
        ("POST /api/rolls", "Create a new roll"),
        ("POST /api/orders", "Create customer order"),
        ("GET /api/orders", "Fetch pending/active orders"),
        ("POST /api/orders/:id/approve", "Approve an order"),
        ("GET /api/dispatched", "Fetch dispatched records"),
        ("GET /api/settings", "Read system settings"),
        ("POST /api/settings", "Update system settings"),
    ]
    for endpoint, purpose in endpoints:
        row = api_table.add_row().cells
        row[0].text = endpoint
        row[1].text = purpose


def build_manual(
    output: str,
    company_name: str,
    prepared_by: str,
    version: str,
    app_name: str,
) -> None:
    doc = Document()
    configure_page(doc)
    set_default_font(doc)

    generated_on = datetime.now().strftime("%d %B %Y")

    add_cover_page(doc, company_name, prepared_by, version, app_name, generated_on)
    add_table_of_contents(doc)
    add_purpose_section(doc, app_name)
    add_overview_section(doc, app_name)
    add_navigation_section(doc)
    add_workflow_section(doc)
    add_module_steps_section(doc)
    add_do_not_modify_section(doc)
    add_settings_and_reports(doc)
    add_troubleshooting(doc)
    add_data_security_support(doc)

    doc.save(output)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a professional DOCX user manual for the Yarn Roll Tracker desktop application."
    )
    parser.add_argument(
        "--output",
        default="Yarn_Roll_Tracker_User_Manual.docx",
        help="Output DOCX file path",
    )
    parser.add_argument(
        "--company",
        default="Client Company",
        help="Company name displayed on the cover page",
    )
    parser.add_argument(
        "--prepared-by",
        default="Implementation Team",
        help="Prepared-by value on the cover page",
    )
    parser.add_argument(
        "--version",
        default="1.0",
        help="Document version",
    )
    parser.add_argument(
        "--app-name",
        default="Yarn Roll Tracking System",
        help="Application name to show in the manual",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    build_manual(
        output=args.output,
        company_name=args.company,
        prepared_by=args.prepared_by,
        version=args.version,
        app_name=args.app_name,
    )
    print(f"User manual created successfully: {args.output}")


if __name__ == "__main__":
    main()
